version: '3.8'

services:
  api-gateway:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - account-service
      - trading-service
      - wallet-service
      - notification-service
      - centralized-logging

  account-service:
    build: ./account-service
    ports:
      - "5001:5001"

  trading-service:
    build: ./trading-service
    ports:
      - "5002:5002"

  wallet-service:
    build: ./wallet-service
    ports:
      - "5003:5003"

  notification-service:
    build: ./notification-service
    ports:
      - "5004:5004"