apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  selector:
    app: account-service
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
