apiVersion: v1
kind: Service
metadata:
  name: account-service-green
spec:
  selector:
    app: account-service
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
